### ISSUE TITLE
Update github link everywhere

### ISSUE THREAD

**Issue by fricoben** [lfglabs-dev/docs.starknet.id#53]
## Description 📹

Update our old https://github.com/starknet-id link to https://github.com/lfglabs-dev everywhere it needs to be updated

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
- [ ] Update https://github.com/lfglabs-dev everywhere

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by Snehagupta1907** [comment]
can i take up this issue ?

**Comment by martinvibes** [comment]
Hey @fricoben can I work on this issue as I have some merged docs on od hack before

**Comment by vestor-dev** [comment]
Hey @fricoben I'm new can I hop on this issue

**Comment by NueloSE** [comment]
@fricoben can i be assigned this task

**Comment by Kingsuite** [comment]
@fricoben can i make this my first issue to the starkquest eco system. kindly assign me

**Comment by OWK50GA** [comment]
Can I work on this?

**Comment by Emmanex01** [comment]
I’d love to work on this task.

**Comment by Benjtalkshow** [comment]
I’d like to help with this.

**Comment by Michaelkingsdev** [comment]
Can I attempt this issue?

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue
My name is Sudipta Paul having experience in fullstack and blockchain for around 1.5 years and want to contribute to the ecosystem.

My approach:

Inspect all the github href links present on the codebase and apply the new github link provided and then running it locally properly to check that all the links works properly and takes user to the required repo.

**Comment by DADADAVE80** [comment]
Can I tackle this one?
